"""added datetime

Revision ID: ae9a025557e1
Revises: 12d4dd621cbd
Create Date: 2020-09-28 12:03:39.642944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9a025557e1'
down_revision = '12d4dd621cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('dateposted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'dateposted')
    # ### end Alembic commands ###
