"""added header image

Revision ID: f47b81e52aff
Revises: b8a531d23b93
Create Date: 2020-10-01 00:43:13.476531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47b81e52aff'
down_revision = 'b8a531d23b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('header_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('blogpost_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blogpost_id'], ['blogposts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogposts', sa.Column('header_img_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'header_img_path')
    op.drop_table('header_image')
    # ### end Alembic commands ###
